export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const SIGN_USER_BEGIN = 'SIGN_USER_BEGIN';
export const SIGN_USER_SUCCESS = 'SIGN_USER_SUCCESS';
export const SIGN_USER_ERROR = 'SIGN_USER_ERROR';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const ADD_FOODY_BEGIN = 'ADD_FOODY_BEGIN';
export const ADD_FOODY_SUCCESS = 'ADD_FOODY_SUCCESS';
export const ADD_FOODY_ERROR = 'ADD_FOODY_ERROR';

export const GET_FOODYS_BEGIN = 'GET_FOODIES_BEGIN';
export const GET_FOODYS_SUCCESS = 'GET_FOODIES_SUCCESS';

export const SET_EDIT_FOODY = 'SET_EDIT_FOODY';
