export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const CHECK_USERNAME_BEGIN = 'CHECK_USERNAME_BEGIN';
export const CHECK_USERNAME_SUCCESS = 'CHECK_USERNAME_SUCCESS';
export const CHECK_USERNAME_ERROR = 'CHECK_USERNAME_ERROR';
