export const CLEAR_ALERT = 'CLEAR_ALERT';

export const GET_MY_PROFILE_BEGIN = 'GET_MY_PROFILE_BEGIN';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_USER_PROFILE_BEGIN = 'GET_USER_PROFILE_BEGIN';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_BEGIN = 'UPDATE_USER_PROFILE_BEGIN';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_ERROR = 'UPDATE_USER_PROFILE_ERROR';
